version: '2'

services:

  elasticsearch:
    build:
      context: elasticsearch/
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - /opt/data/elasticNode0:/usr/share/elasticsearch/data/nodes
      #Above used to store elastic data in persistant location
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx10g -Xms10g"
      # You may want increase above as 1G ram not much for elastic
    networks:
      - elk

  logstash:
    build:
      context: logstash/
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  redis:
    build:
      context: redis/
    ports:
      - "127.0.0.1:6379:6379"
    networks:
      - elk

  nxlog:
    build:
      context: nxlog/
    ports:
      - "1514:1514"
    volumes:
      - ../net2Host:/opt/net2Host/:ro
    #  Used for development overload git repo with host one for Dev
    networks:
      - elk
    depends_on:
      - redis

  brologread:
    build:
      context: brologread/
    volumes:
      - /var/log/bro:/var/log/bro
      - /var/spool/bro:/var/spool/bro
      #Alter above line to point at bro current folder
      - ../net2Host:/opt/net2Host/:ro
      # Used for development overload git repo with host one for Dev
    networks:
      - elk
    depends_on:
      - redis

  correlate:
    build:
      context: correlate/
    volumes:
      - ../net2Host:/opt/net2Host/:ro
    #  Used for development overload git repo with host one for Dev
    networks:
      - elk
    depends_on:
      - elasticsearch
      - redis

networks:

  elk:
    driver: bridge
